version: '3'
services:
    bcb:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
        ports: 
            - 8082:8082
    erp-itau:
        image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
        ports: 
            - 9091:9091

    key-manager-grpc:
        image: "key-manager-server:v1"
        ports:
            - 50050:50051
        environment: 
            DB_URL: jdbc:postgresql://postgres:5432/bd_pix
            ERP_URL: erp-itau:9091
            BCB_URL: bcb:8082
        restart: always
    key-manager-rest:
        image: "key-manager-rest:v1"
        ports:
            - 8010:8080
        environment: 
            GRPC_URL: key-manager-grpc:50051
        restart: always
    postgres:
        image: "postgres:alpine"
        volumes: 
            - postgres-volume:/var/lib/postgresql/data
        ports:
            - 5434:5432
        environment: 
            POSTGRES_PASSWORD: 1234567
            POSTGRES_USER: postgres
            POSTGRES_DB: bd_pix
volumes:
    postgres-volume:
