micronaut:
  application:
    name: keyManager

grpc:
  server:
    port: localhost:5051

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/bd_keymanager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234567
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

jpa.default.properties.hibernate.show_sql: true

jpa.default.properties.hibernate.format_sql: true


